### PR TITLE
Rebased on goodtables.next codebase

### LINKED ISSUE #36: General pipeline refactoring
There are a few things I want to change, but as long as tests are passing I'm *not* focussing on it now. Rather, this issue is a placeholder for notes on changes I *want* make while working on other things.

* [x] Get rid of all the run_* stuff in the pipeline calling code per validator - it is enough to call run on each validator
* [x] Tidy up all the stuff around dry_run and transform
* [ ] Refactor all distinct validation checks to generators
* [x] Fix workspace and let it support both an s3 directory and a local directory (use https://github.com/pudo/barn for that - it does everything I need already)
* [ ] Don't need the utf-8 textstream until we start reading the data, so only need to do the conversion as we iterate over data
* [ ] Remove all the `help` and `help_edit` keys on the result dicts

### LINKED ISSUE #66: Add support for tabular data packages
It would be very useful to be able to check for validity of [tabular data packages](http://dataprotocols.org/tabular-data-package/) by using the goodtables CLI. Ideally it should:
* *schema validation*: check whether the included `datapackage.json` file conforms to the tabular data package specification
  * consequently, as that is an extension of the [data package specification](http://dataprotocols.org/data-packages/), it must conform to that as well
  * check if the included schema conforms to [json table schema](http://dataprotocols.org/json-table-schema/) specification
* *data validation*: check if the resources described in it exist, are csv files and the data conforms to the [json table schema](http://dataprotocols.org/json-table-schema/) included in the `datapackage.json`

Note: this idea originated from a discussion of issue [#73](https://github.com/okfn/publicbodies/issues/73) of [publicbodies](https://github.com/okfn/publicbodies).

### LINKED ISSUE #75: Update management tools
- [ ] https://github.com/okfn/oki-py compliance
- [ ] versioned milestones instead of `Current` (@pwalsh WDYT? - for semver and our tagged publication model it looks more appropriate for me). Example - https://github.com/frictionlessdata/tabulator-py/milestones

### LINKED ISSUE #91: Be specific about too many or too few columns in a row
atm just get: "The row dimensions are incorrect compared to headers."

Why not say whether we had too many or too few specifically ...

```
+---------------+---------------+-------------+-------------------------------------------------------+
| result_name   | result_id     |   row_index | result_message                                        |
+===============+===============+=============+=======================================================+
| Defective Row | structure_003 |           1 | The row dimensions are incorrect compared to headers. |
+---------------+---------------+-------------+-------------------------------------------------------+
| Defective Row | structure_003 |           2 | The row dimensions are incorrect compared to headers. |
+---------------+---------------+-------------+-------------------------------------------------------+
```

### LINKED ISSUE #92: Header column is empty should tell me which column
Be nice to be told *which* header column is empty ...

```
+----------------+---------------+-------------+-------------------------------------------------------+
| result_name    | result_id     |   row_index | result_message                                        |
+================+===============+=============+=======================================================+
| Missing Header | structure_001 |           0 | Headers column is empty.                              |
```

### LINKED ISSUE #93: Schema Processor reports structural errors
Here is an example where Schema Processor is run and produces what seem like "structural" errors (except for last one).

* Structure processor produces: "The row dimensions are incorrect compared to headers" which similar but different (and produces a different number of errors).
* I also note there is an error with row_index = 0 which is odd (which is the header row).
* Seems to me that we should seek to suppress structural errors in the Schema processor - though acknowledge this is a pretty subtle and complex area (is this a schema or a structural error - when is structural stuff bad enough that we cannot proceed with schema processing ...)

```
+----------------------+-------------+-------------+--------------------------------------------------------+
| result_name          | result_id   |   row_index | result_message                                         |
+======================+=============+=============+========================================================+
| Incorrect Dimensions | schema_002  |           0 | The row dimensions do not match the header dimensions. |
+----------------------+-------------+-------------+--------------------------------------------------------+
| Incorrect Dimensions | schema_002  |           1 | The row dimensions do not match the header dimensions. |
+----------------------+-------------+-------------+--------------------------------------------------------+
| Incorrect Dimensions | schema_002  |           2 | The row dimensions do not match the header dimensions. |
+----------------------+-------------+-------------+--------------------------------------------------------+
| Incorrect Dimensions | schema_002  |           3 | The row dimensions do not match the header dimensions. |
+----------------------+-------------+-------------+--------------------------------------------------------+
| Incorrect Dimensions | schema_002  |           4 | The row dimensions do not match the header dimensions. |
+----------------------+-------------+-------------+--------------------------------------------------------+
| Incorrect Type       | schema_003  |           5 | The value "2015" in column "Date" is not a valid Date. |
+----------------------+-------------+-------------+--------------------------------------------------------+
```

Source data is:

```
Date,Country,Number,                                                                     
2015-01-01,3,20.3
2015-02-01,United States,23.5,,
2015-02,United States,x23.5,,, 
,,
2015,United States,x23.5,
```

### LINKED ISSUE #95: Support validating JSON input data as well as XLS and CSV

### LINKED ISSUE #106: Deep refactoring
# Overview

@pwalsh's wrote:

```
goodtables is very little apart from tabulator + jsontableschema + data-quality-spec + an output report.

Of course there will be issues when you port, but the bottom line is we’ll probably reduce 100s to 1000s of lines of code, some inconsistent internal APIs, and you’ll likely also learn some edge cases and stuff for tabular data handling that can feed back into tabulator

the important thing is: goodtables is the basis for a product, and it is more important, right now, to move on shipping goodtables than to get the other libs to v1, etc

getting them to v1 can be a by-product of goodtables, not the other way around

just because there is lots of interest in goodtables, and before we start the test pilots around GT from beg. October onwards, it would be better to be on a stabler base, as the GT needs serious refactoring by now with all we learned
---
`goodtables.datatable`: completely replace with `tabulator`, but in the code of datatable, might be some edge case handling that is useful, so check it.

- https://github.com/frictionlessdata/goodtables/tree/master/goodtables/datatable
- also in georgiana’s branch she found some more error handling edge cases here ( https://github.com/georgiana-b/goodtables/commit/7e9da1e480938b9c197e91e5d9c79ccbc5c12fa8 )  
----
`goodtables.cli`: should be easy, and I assume you will have good ideas

- https://github.com/frictionlessdata/goodtables/tree/master/goodtables/cli
----
`goodtables.pipeline.Pipeline`: Pretty easy once datatable is replaced by tabulator, and now using jsontableschema-py to replace lots of hardcoded stuff

- https://github.com/frictionlessdata/goodtables/blob/master/goodtables/pipeline/pipeline.py
----

`goodtables.pipeline.Batch`: *very* useful batch pipeline runner. Needs proper parallelization

- https://github.com/frictionlessdata/goodtables/blob/master/goodtables/pipeline/batch.py
- georgiana tried to parallelize here but forgot about shared state: https://github.com/georgiana-b/goodtables/commit/5514c3cb769c54a5dbe415df61cf406812600c83
---- 

`goodtables.processors`: they will essentially be tabulator processors I guess. Again, some hard coded stuff from before we had libs, or really understood the desirable API design. A `pipeline` calls processors, and note we also have an API for custom processors - the tabulator API for that is better

- https://github.com/frictionlessdata/goodtables/tree/master/goodtables/processors (edited)
---
Reports: GoodTables generates reports, and has a few output formats, as well as some tricky (ugly) stuff to shape the output. I absolutely encourage you to break the API of reports for something better, and even preferable, a format that can be streamed (emit report objects as they occur - if possible…)

- `tellme`: rufus wanted me to make that a distinct lib: IMHO it is not really worth it: https://github.com/okfn/tellme but it is what is used for report objects
- “report results”: you’ll see various places with report result definitions ( eg: https://github.com/frictionlessdata/goodtables/blob/master/goodtables/processors/schema.py#L11 ), including recent ones that that georgiana added in unusual places. these should be replaced by use of the new, generic `data-quality-spec`
- data-quality-spec: https://github.com/frictionlessdata/data-quality-spec (edited)
---

- note `self.report` and `def set_report_meta` here: https://github.com/frictionlessdata/goodtables/blob/master/goodtables/pipeline/pipeline.py#L280 (edited)

inspect with ipdb on some sample datasets and you’ll see what goes on there

a better design can come out of seeing what we have there

------
 
Lastly! “Hooks”! I built a simple hook system into `pipeline.Pipeline` and `pipeline.Batch`: both take a `post_task` argument. We use this, for example, in `data-quality-cli` and also in `goodtables-web` to modify reports. At the time, I kind of needed it, but I am honestly not sure any more if it is required… maybe better way to solve same problem:

- https://github.com/frictionlessdata/goodtables/blob/master/goodtables/pipeline/pipeline.py#L79
```

### LINKED ISSUE #107: Absolute row limit maximum in Pipeline
To start, I just wanted to say that I think this is a really great package and something we're interested in integrating into some of our workflows.

I have a questions about `ROW_LIMIT_MAX` in `pipeline.Pipeline`. If I'm reading everything correctly this sets an absolute upper limit on the maximum number of rows that can be processed. I'm curious about the reasoning for an absolute upper limit as opposed to sticking with a default number of rows and letting the user override it. The reason I ask is that I'm interested in using the package to do QC on entire data files and this would seem to prevent me from doing that for any reasonably large datafile.

### LINKED ISSUE #117: Update schema if extra/unordered headers has happened
# Overview

Those checks should update `fields` list.

### PR DESCRIPTION
**Pull request by roll**
# Overview

Codebase update.

# Issues

- fixes #36
- fixes #66
- fixes #75 
- fixes #91 
- fixes #92 
- fixes #93 
- fixes #95 
- fixes #106 
- fixes #107
- fixes #117

### CODE REVIEW

**Comment by roll** [comment]
@pwalsh 
Please take a look - for related issues I've added examples of goodtables.next output or design notes.

cc @amercader @georgiana-b

**Comment by pwalsh** [comment]
@roll any way to run tests of this code against a lot of those test files I had?

**Comment by roll** [comment]
@pwalsh 
I've created issue for it - https://github.com/frictionlessdata/goodtables-py/issues/127 - will be adding it next

**Comment by pwalsh** [comment]
- missing desc. https://github.com/frictionlessdata/goodtables-py/blob/next-initial/setup.py#L51

- do we really want a CKAN profile? is this logic enough to get tabular data out of a CKAN instance (i guess not, and I think there are lots of custom things to consider)? https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/profiles/ckan.py#L15

- I'm not a fan of passing in data (errors and table in this case), modifying it, and then not returning that modified data. https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/profiles/datapackage.py#L15

Based on the way [profiles are used here](https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/inspector.py#L79), I don't see why the profile function needs errors and table passed in as arguments - they are always empty. Why not get rid of the empty list assignments and have

```
errors, tables = profile_handler(source, **options)  # sidenote: handler because more meaningful than func?
```

**Comment by pwalsh** [comment]
@roll I'm done with my review, as above.

**Comment by roll** [comment]
@pwalsh 
Thanks, pretty comprehensive review!

---

> where are checks for things like file not found, http , io error, etc. coming from, if not here https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/checks/__init__.py#L1

I've tried to have check for every error but I've failed with this idea as not flexible enough. So for now source errors could be emitted:
- by profiles
- by framework itself - https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/inspector.py#L147

It gives much more flexibility now and in a future (e.g. when we'll move jts validation on table level - it will be not an exception handling but iterating over errors so `check(exception)` will not work)

---

I've added issues based on comments (as we've discussed to do first big chuck of work and then split additional work into small parts):
- #124
- #127 
- #129 
- #130 
- #131 

---

And I've pushed commits covering other comments.

**Comment by pwalsh** [comment]
@roll ok, but I do think that this is critical before merging this onto master, as without it, we've lost critical functionality:

https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/inspector.py#L148

**Comment by roll** [comment]
@pwalsh 
This one we're merging to `next` branch (check PR header). Then we will close other issues thru PRs to next branch. And then we will merge `next` to `master` (when it will be `master` ready, tested etc).

So I have no preference I could include https://github.com/frictionlessdata/goodtables-py/blob/next-initial/goodtables/inspector.py#L148 to this PR or it as a next PR.

**Comment by pwalsh** [comment]
Ok. I don't know why the extra step, but go for it then, and I suggest to address these errors asap on the next branch.

**Comment by roll** [comment]
Ok. Thanks. Extra step because the code is not master ready but I want to make closing other issue reviwable by the team. To do not put everything in one gigantic PR (it's already pretty big though=).

**Comment by pwalsh** [comment]
Great. Let's go!

**Pull request merged**
