### PR TITLE
Fixed miessage_substitutions in missing_header

### LINKED ISSUE #337: Validate throws exception when order_fields=True and skip_checks=['extra-header']
# Overview

We have noticed a use case where the validation crashes. (we are using goodtables@2.4.7)

Our validation rules allow data with different columns order (`order_fields=True`), extra-headers and missing-headers (if not marked as required in schema).

Here is the stacktrace of the thrown exception:
```python
Traceback (most recent call last):
  File "bug.py", line 67, in <module>
    report = validate(DESCRIPTOR, skip_checks=['extra-header'], order_fields=True, infer_fields=False)
  File "/home/didiez/bug_goodtables/env/lib/python3.7/site-packages/goodtables/validate.py", line 80, in validate
    report = inspector.inspect(source, **options)
  File "/home/didiez/bug_goodtables/env/lib/python3.7/site-packages/goodtables/inspector.py", line 82, in inspect
    table_warnings, table_report = task.get()
  File "/home/didiez/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/didiez/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/didiez/bug_goodtables/env/lib/python3.7/site-packages/goodtables/inspector.py", line 222, in __inspect_table
    errors += (check_func(header_cells, sample) or [])
  File "/home/didiez/bug_goodtables/env/lib/python3.7/site-packages/goodtables/checks/missing_header.py", line 26, in missing_header
    'field_name': '"{}"'.format(cell['field'].name),
AttributeError: 'NoneType' object has no attribute 'name'
```

The bug is reproducible executing the following script:
```python
# !/usr/bin/python
# -*- coding: utf-8 -*-

import json
from goodtables import validate

# example resource and schema
DESCRIPTOR = {
    "resources": [
        {
            "name": "people",
            "data": [
                ["id", "name", "surname", "dob", "country"],
                [1, "Stephen", "Hawking", "1942-01-08", "england"],
                [2, "Marie", "Curie", "07/11/1867", "poland"],
                [3, "Ada", "Lovelace", "1815-12-10", "england"],
                [4, None, "Darwin", "1809-02-12", "england"],
                [5, "Isaac", "Newton", "1642-12-25", "england"],
                [5, "Galileo", "Galilei", "1564-02-15", "italy"],
                [7, "Leonardo", "da Vinci", "1452-04-15", "italy"]
            ],
            "schema": {
                "fields": [{
                    "name": "id",
                    "type": "number",
                    "constraints": {
                        "required": True,
                        "unique": True
                    }
                },
                    {
                        "name": "name",
                        "type": "string",
                        "constraints": {
                            "required": True
                        }
                    },
                    {
                        "name": "surname",
                        "type": "string"
                    },
                    {
                        "name": "gender",
                        "type": "string",
                        "constraints": {
                            "enum": ["male", "female"]
                        }
                    },
                    {
                        "name": "dob",
                        "type": "date",
                        "constraints": {
                            "required": True
                        }
                    },
                    {
                        "name": "more",
                        "type": "string"
                    },
                ]
            }
        }
    ]
}

# Allow extra headers AND different columns order
report = validate(DESCRIPTOR, skip_checks=['extra-header'], order_fields=True, infer_fields=False)
print(json.dumps(report))
```

Trying to debug the error, I have ended up at some code related with #298 in `non_matching_header.py` but I'm not sure how to fix it without breaking other things.
https://github.com/frictionlessdata/goodtables-py/blob/90ca8e9e44ba87e24784c3c3157068ad7fd204f6/goodtables/checks/non_matching_header.py#L65

When commenting out that line, the validation works again (at least without throwing an exception) but gives us a report with **wrong** `missing-header` and `non-matching-header` errors.

If added `missing-header` to skip_checks, the validation doesn't break with exception but the report returns wrong `non-matching-header`and `missing-value`validation errors

---

Please preserve this line to notify @roll (lead of this repository)

### LINKED ISSUE #338: Use field_name in 'missing-header' errors
# Overview

When validating data with `order_fields=True`, the default message for the missing-header check gives no clue about the missing header, showing `'There is a missing header in column None'.`

When `order_fields=True`, the message would be more useful if references the `field_name`, for example: There is a missing header with name {field_name}.

This could be fixed when creating the error in the missing_header check:
```python
error = Error(
    'missing-header',
    cell,
    message="There is a missing header with name {field_name}" + (" in column {column_number}" if cell.get('column-number') is not None else ""),
    message_substitutions=message_substitutions
)
```

---

Please preserve this line to notify @roll (lead of this repository)

### PR DESCRIPTION
**Pull request by roll**
- fixes #338
- fixes #337

### CODE REVIEW

**Comment by roll** [comment]
Hi @didiez,

can you please check if it solves the problem from #337

**Comment by didiez** [comment]
Hi @roll 
Yes, it seems that the fix solves the error reported in #337, but it would also be great if the `field_name` could be interpolated in the default message registered in `spec` for missing-header errors.

The error reported with this fix gives no clue about the missing column name. With `order_fields=True` the column number is not relevant.
```json
{
    "code": "missing-header",
    "message": "There is a missing header in column None",
    "message-data": {"field_name": "more"},
    "row": [
        1,
        "Stephen",
        "Hawking",
        "1942-01-08",
        "england"
    ]
}
```

With `f'strings` could be something like this (not valid with `string.format(..)`)
```python
f"There is a missing header with name '{field_name}'{f' in column {column_number}' if column_number else ''}"
```

We are overriding the default spec message to fix this issue, but I think the lack of `column_number` when `order_fields=True` is something to be aware of. There are other messages in `spec.json` that use only the column_number, which ouputs 'None' when `order_fields=True`
```python
spec['errors']['missing-header']['message'] = "There is a missing header with name '{field_name}' in column {column_number}"
```

**Comment by didiez** [comment]
Sorry, I forgot I opened an issue #338 about my last comment, which is closely related to this pull request.

Thanks @roll

**Comment by roll** [comment]
Thanks @didiez, I'll update this tomorrow to handle both issues

**Comment by roll** [comment]
Hi @didiez, 

I'm not in a great position time-wise now to dive deeper into the problem so I've added a temporary fix to show the field name. 

Will it work, for now?

**Comment by didiez** [comment]
Sure @roll, the temporary fix is enough. Thanks for your time!

**Pull request merged**
